/** Regenerate only the transitive protocol types consumed by Hush from the installed Codex. */
import {execFileSync} from 'node:child_process';
import {mkdtempSync, readFileSync, writeFileSync, mkdirSync, rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {dirname, join, resolve} from 'node:path';

const roots = ['InitializeParams', 'InitializeResponse',
  ...['ThreadStartParams', 'ThreadStartResponse', 'ThreadSetNameParams', 'ThreadSetNameResponse', 'ThreadResumeParams', 'ThreadResumeResponse',
    'ThreadListParams', 'ThreadListResponse', 'ThreadTurnsListParams', 'ThreadTurnsListResponse',
    'ThreadItemsListParams', 'ThreadItemsListResponse', 'TurnStartParams', 'TurnStartResponse',
    'TurnSteerParams', 'TurnSteerResponse', 'TurnInterruptParams',
    'CommandExecutionRequestApprovalParams', 'CommandExecutionRequestApprovalResponse',
    'FileChangeRequestApprovalParams', 'FileChangeRequestApprovalResponse',
    'PermissionsRequestApprovalParams', 'PermissionsRequestApprovalResponse',
    'ToolRequestUserInputParams', 'ToolRequestUserInputResponse',
    'McpServerElicitationRequestParams', 'McpServerElicitationRequestResponse',
  ].map(name => `v2/${name}`)];
const temp = mkdtempSync(join(tmpdir(), 'hush-protocol-'));
const output = resolve('src/protocol');
const version = execFileSync('codex', ['--version'], {encoding: 'utf8'}).trim();
try {
  execFileSync('codex', ['app-server', 'generate-ts', '--experimental', '--out', temp], {stdio: 'pipe'});
  const files = new Map();
  function collect(name) {
    const relative = `${name}.ts`;
    if (files.has(relative)) return;
    const source = readFileSync(join(temp, relative), 'utf8');
    files.set(relative, source.replace(/from "([^"]+)"/g, 'from "$1.js"'));
    for (const match of source.matchAll(/from "([^"]+)"/g)) {
      collect(join(dirname(name), match[1]));
    }
  }
  roots.forEach(collect);
  rmSync(output, {recursive: true, force: true});
  for (const [name, source] of files) {
    mkdirSync(dirname(join(output, name)), {recursive: true});
    writeFileSync(join(output, name), source);
  }
  writeFileSync(join(output, 'version.ts'), `// Generated by scripts/protocol.mjs.\nexport const testedCodexVersion = ${JSON.stringify(version)};\n`);
  console.log(`Generated ${files.size} protocol types from ${version}. Run npm run check and npm run smoke before accepting an upgrade.`);
} finally {
  rmSync(temp, {recursive: true, force: true});
}
